# A sample TOML config file.
[development]
server = "192.168.1.1"  
port = 8080  
connection_max = 100  
enabled = true

[staging]
server = "192.168.1.2"  
port = 8090  
connection_max = 200  
enabled = true

[production]
server = "192.168.1.3"  
port = 9000  
connection_max = 5000  
enabled = true 

[RPCname]
aut="172.17.42.1:9877"
dash=9878
shop=9879
prod=9880
news=9881
tmpl=9882
page=9883
ord=9884
camp=9885
shipper=9886
cus=9887
rep=9888
[dbsession]
h="172.17.42.1:27017"
d="session"
u="sssex"
p="@234.sex"
[config]
domainallow="http://localhost.com,http://duyhf.noip.me,http://localhost:8080"
